# snakemake tutorial config file

# specify samples
samples:
    A: data/samples/A.fastq
    B: data/samples/B.fastq
    C: data/samples/C.fastq

# specify prior mutation rate for variant calling
prior_mut_rate: 0.001
