[workspace]
authors = ["Cindy Liang <celiang@ucsc.edu>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-tutorial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake-minimal = ">=8.4.4"
jinja2 = "*"
matplotlib = "*"
graphviz = "*"
bcftools = ">=1.19"
samtools = ">=1.19"
bwa = "~=0.7.17"
pygments = "*"

[pypi-dependencies]
pysam = "==0.22"
