# usage examples
# snakemake --executor slurm --default-resources --jobs 1

configfile: "config.yaml"

SAMPLES = ["A", "B", "C"]

rule all:
    input:
        expand("hello_{sample}.txt", sample=SAMPLES)

rule hello:
    output:
        "hello_{sample}.txt"
    shell:
        """
        echo "Hello from $(hostname) — sample {wildcards.sample}, job $SLURM_JOB_ID" > {output}
        """
